#!/usr/bin/env python3
"""Repeatable combat probes, not a substitute for human difficulty testing.

Run: uv run --directory apps/server python ../../tools/playtest/playtest.py
A reactive bot fights opening, depths, Warden and Mirror encounters with each
weapon. Opening compares solo and twin play; Mirror is solo, as in the story. Checkpoints are isolated; no player save is changed.
"""
import argparse
import json
import sys
from pathlib import Path
from tempfile import TemporaryDirectory

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / 'apps/server'))
from mirrorbound.api.session import GameSession
from mirrorbound.game.entities.entity import Vec2
from mirrorbound.game.entities.player import PlayerInput
from mirrorbound.game.world import save

WEAPONS = ('iron_sword', 'hunter_bow', 'ember_staff', 'frost_staff')
DT = 1 / 60


def probe(seed, weapon, twin, max_ticks=3600, encounter="opening"):
    area = {'opening':'wakewood_crypt','depths':'wakewood_crypt','warden':'ashen_deep','mirror':'mirror_sanctum'}[encounter]
    s = GameSession('balance-probe', seed=seed, record=False, start_area=area)
    s.state.player.inventory.add_weapon(weapon)
    s.state.player.level = {'opening':1,'depths':3,'warden':5,'mirror':6}[encounter]
    s.state.player.recompute_max_health()
    if twin:
        s.state.twin.awaken(s.state.player.position, 'Probe')
    s._enter_room(s.dungeon.rooms[1 if encounter == 'opening' else -1], from_side='south')
    initial = len(s.state.get_active_enemies())
    for elapsed in range(max_ticks):
        p = s.state.player
        target = s.state.nearest_enemy(p.position)
        if target is None or p.state == 'dead':
            break
        diff = target.position - p.position
        distance = diff.length()
        # The same simple policy in every case: approach melee, keep ranged
        # spacing, sidestep a telegraph, cast affordable/recharged abilities.
        reach = p.weapon.range * (.75 if p.weapon.is_melee else .65)
        move = diff.normalized() if distance > reach else Vec2()
        if not p.weapon.is_melee and distance < reach * .6:
            move = -diff.normalized()
        if target.is_winding_up and distance < target.enemy_def.attack_range + 35:
            move = diff.normalized().perpendicular()
        ability = None
        for slot in (1, 2):
            spec = p.ability_in_slot(slot)
            if spec is None or not p.can_use_ability(spec)[0]:
                continue
            if spec.type.value == 'heal' and p.health > p.max_health - 25:
                continue
            if spec.type.value in ('nova','cone') and distance > spec.area + target.radius:
                continue
            ability = slot
            break
        s.pending_input = PlayerInput(move_x=move.x, move_y=move.y, aim_x=diff.x, aim_y=diff.y,
                                      attack=p.can_attack(), ability=ability)
        s.step(DT)
        if elapsed % 3 == 0:
            s.snapshot()  # normal event draining and detail cadence
    result = {'encounter':encounter,'seed':seed,'weapon':weapon,'twin':twin,'seconds':round((elapsed+1)*DT,2),
              'cleared':not s.state.get_active_enemies(), 'initialEnemies':initial,
              'kills':s.state.stats.enemies_killed, 'health':round(s.state.player.health,1),
              'damageTaken':round(s.state.stats.damage_taken,1),'casts':s.state.stats.abilities_cast,
              'twinKills':s.state.twin.kills,'error':s.last_error}
    s.stop()
    return result


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output', type=Path)
    args=parser.parse_args()
    with TemporaryDirectory(prefix='mirrorbound-playtest-') as directory:
        save.SAVE_DIR=Path(directory)
        rows=[probe(seed,weapon,twin) for seed in (1,5,19) for weapon in WEAPONS for twin in (False,True)]
        # Replay the inputs generated by this policy: outcomes must match.
        assert rows[0] == probe(1,WEAPONS[0],False)
        rows += [probe(seed,weapon,encounter != 'mirror',encounter=encounter)
                 for encounter in ('depths','warden','mirror') for seed in (1,5,19) for weapon in WEAPONS]
    result={'scenario':'reactive scripted player; opening level 1, depths 3, Warden 5, Mirror 6; no skills or healing items',
            'cases':len(rows),'cleared':sum(row['cleared'] for row in rows),
            'crashes':sum(row['error'] is not None for row in rows),'results':rows}
    data=json.dumps(result,indent=2)+'\n'
    if args.output:
        args.output.write_text(data)
    print(data)

if __name__ == '__main__':
    main()
