#!/usr/bin/env python3
"""Floor tiles: three sheets of twelve, sliced straight into atlases.

Every other sheet in the pipeline is artwork on a background that has to be
found and trimmed to. Tiles are the opposite: each cell is filled corner to
corner on purpose, nothing is keyed out, and a trim would be actively wrong --
the whole point of a tile is that its pattern runs off all four edges. So this
does not go through `atlaslib` at all. It slices the grid, resamples each cell
to the size the floor is actually drawn at, and writes the atlas.

Run by `npm run assets`, after `build_atlas.py`.
"""

from __future__ import annotations

import json
from pathlib import Path

from PIL import Image

WEB = Path(__file__).resolve().parents[1]
ASSETS = WEB.parents[1] / "assets" / "world"
OUT = WEB / "public" / "game"
TS_OUT = WEB / "src" / "game" / "animation"

#: World units per tile. Must match `TILE` in `src/game/constants.ts`: the
#: floor is composed at world scale and `drawFrame` does not resample, so a
#: frame of any other size would not line up with the grid.
TILE = 32

#: The grid every tile sheet is drawn on, left to right and top down.
COLS, ROWS = 4, 3

#: Frame names, in sheet order. These are the names the renderer asks for, and
#: they carry the variant index because the floor picks between variants by a
#: hash -- see `tileVariant` in `world/floor.ts`.
NAMES = (
    "grass0", "grass1", "grass2", "dirt0",
    "dirt1", "path0", "path1", "stone0",
    "stone1", "stone2", "water", "wall",
)

BIOMES = ("grove", "ruins", "crypt")


def slice_sheet(path: Path) -> list[Image.Image]:
    """Twelve cells, each resampled to one tile."""
    sheet = Image.open(path).convert("RGBA")
    cw, ch = sheet.width // COLS, sheet.height // ROWS
    if cw * COLS != sheet.width or ch * ROWS != sheet.height:
        raise SystemExit(
            f"{path.name}: {sheet.width}x{sheet.height} is not a clean "
            f"{COLS}x{ROWS} grid (cells would be {sheet.width / COLS}x{sheet.height / ROWS})"
        )
    out = []
    for row in range(ROWS):
        for col in range(COLS):
            cell = sheet.crop((col * cw, row * ch, (col + 1) * cw, (row + 1) * ch))
            # LANCZOS rather than NEAREST: these are painted surfaces, not
            # pixel art, and the reduction is severe (362 -> 32). Point
            # sampling at that ratio throws away almost every speckle and
            # leaves a flat colour with three dots on it.
            out.append(cell.resize((TILE, TILE), Image.LANCZOS))
    return out


def build(biome: str) -> None:
    source = ASSETS / f"tiles-{biome}.png"
    if not source.exists():
        print(f"tiles-{biome}: no source, skipping")
        return
    cells = slice_sheet(source)

    name = f"tiles{biome.capitalize()}"
    atlas = Image.new("RGBA", (TILE * len(cells), TILE), (0, 0, 0, 0))
    entries: dict[str, dict] = {}
    for i, (cell, frame) in enumerate(zip(cells, NAMES)):
        atlas.paste(cell, (i * TILE, 0))
        entries[frame] = {
            "frame": {"x": i * TILE, "y": 0, "w": TILE, "h": TILE},
            "rotated": False,
            # Never trimmed: a tile is its whole cell, edge to edge.
            "trimmed": False,
            "spriteSourceSize": {"x": 0, "y": 0, "w": TILE, "h": TILE},
            "sourceSize": {"w": TILE, "h": TILE},
        }

    out_dir = OUT / name
    out_dir.mkdir(parents=True, exist_ok=True)
    atlas.save(out_dir / f"{name}.png", optimize=True)
    (out_dir / f"{name}.json").write_text(json.dumps({
        "frames": entries,
        "meta": {
            "app": "scripts/build_tiles.py",
            "image": f"{name}.png",
            "format": "RGBA8888",
            "size": {"w": atlas.width, "h": atlas.height},
            "scale": "1",
        },
    }, indent=1), encoding="utf-8")

    size_kb = (out_dir / f"{name}.png").stat().st_size / 1024
    print(f"{name}: atlas {atlas.width}x{atlas.height} ({size_kb:.0f} KB)  {len(cells)} tiles")


def write_typescript() -> None:
    names = ",\n  ".join(f'"{n}"' for n in NAMES)
    keys = ",\n  ".join(f'{b}: "tiles{b.capitalize()}"' for b in BIOMES)
    TS_OUT.mkdir(parents=True, exist_ok=True)
    (TS_OUT / "tilesAtlas.generated.ts").write_text(
        "// GENERATED by scripts/build_tiles.py -- do not edit by hand.\n"
        "// Regenerate with: npm run assets\n\n"
        "/** One drawn tile atlas per biome, keyed by the biome's own name. */\n"
        "export const TILES_TEXTURE_KEY = {\n  "
        f"{keys},\n"
        "} as const;\n\n"
        "/** Every frame a tile atlas carries, in sheet order. */\n"
        "export const TILES_FRAMES = [\n  "
        f"{names},\n"
        "] as const;\n\n"
        f"/** Tiles are drawn at world scale; this must equal TILE. */\nexport const TILES_SIZE = {TILE} as const;\n",
        encoding="utf-8",
    )
    print(f"wrote {TS_OUT.name}/tilesAtlas.generated.ts")


if __name__ == "__main__":
    for biome in BIOMES:
        build(biome)
    write_typescript()
