// GENERATED by scripts/build_atlas.py -- do not edit by hand.
// Regenerate with: npm run assets

export const ABILITYICONS_TEXTURE_KEY = "abilityIcons" as const;

/** How tall the character itself is inside the frame box, 0..1.
 *  Cells are padded by trails and motion range, so this -- not the frame
 *  height -- is what two characters must be compared on to size them
 *  relative to each other. */
export const ABILITYICONS_BODY_RATIO = 0.89451 as const;

/** Every frame shares this source box, so one origin works for all of them. */
export const ABILITYICONS_FRAME_SIZE = { width: 123, height: 132 } as const;

/** Origin on the body centre and its vertical centre. */
export const ABILITYICONS_ANCHOR = { x: 0.47154, y: 0.50000 } as const;

export const ABILITYICONS_FRAMES = {
  icon: ["arcane_bolt", "shadow_dash", "mending_light", "aegis"],
  icon_b: ["fist", "daggers", "eye", "hourglass"],
} as const;

export type AbilityiconsClip = keyof typeof ABILITYICONS_FRAMES;
