// GENERATED by scripts/build_atlas.py -- do not edit by hand.
// Regenerate with: npm run assets

export const ACOLYTEATTACK_TEXTURE_KEY = "acolyteAttack" as const;

/** How tall the character itself is inside the frame box, 0..1.
 *  Cells are padded by trails and motion range, so this -- not the frame
 *  height -- is what two characters must be compared on to size them
 *  relative to each other. */
export const ACOLYTEATTACK_BODY_RATIO = 0.95203 as const;

/** Every frame shares this source box, so one origin works for all of them. */
export const ACOLYTEATTACK_FRAME_SIZE = { width: 446, height: 469 } as const;

/** Origin on the body centre and its feet. */
export const ACOLYTEATTACK_ANCHOR = { x: 0.51794, y: 0.99360 } as const;

export const ACOLYTEATTACK_FRAMES = {
  a: ["f-00", "f-01", "f-02", "f-03"],
  b: ["f-04", "f-05", "f-06", "f-07"],
} as const;

export type AcolyteattackClip = keyof typeof ACOLYTEATTACK_FRAMES;
