// GENERATED by scripts/build_atlas.py -- do not edit by hand.
// Regenerate with: npm run assets

export const ALERTMARK_TEXTURE_KEY = "alertMark" as const;

/** How tall the character itself is inside the frame box, 0..1.
 *  Cells are padded by trails and motion range, so this -- not the frame
 *  height -- is what two characters must be compared on to size them
 *  relative to each other. */
export const ALERTMARK_BODY_RATIO = 0.73903 as const;

/** Every frame shares this source box, so one origin works for all of them. */
export const ALERTMARK_FRAME_SIZE = { width: 156, height: 433 } as const;

/** Origin on the body centre and its vertical centre. */
export const ALERTMARK_ANCHOR = { x: 0.44872, y: 0.49654 } as const;

export const ALERTMARK_FRAMES = {
  mark: ["mark-00", "mark-01", "mark-02", "mark-03"],
  mark_b: ["mark-04", "mark-05"],
} as const;

export type AlertmarkClip = keyof typeof ALERTMARK_FRAMES;
