// GENERATED by scripts/build_atlas.py -- do not edit by hand.
// Regenerate with: npm run assets

export const BARSPLATES_TEXTURE_KEY = "barsPlates" as const;

/** How tall the character itself is inside the frame box, 0..1.
 *  Cells are padded by trails and motion range, so this -- not the frame
 *  height -- is what two characters must be compared on to size them
 *  relative to each other. */
export const BARSPLATES_BODY_RATIO = 0.44949 as const;

/** Every frame shares this source box, so one origin works for all of them. */
export const BARSPLATES_FRAME_SIZE = { width: 177, height: 198 } as const;

/** Origin on the body centre and its vertical centre. */
export const BARSPLATES_ANCHOR = { x: 0.49718, y: 0.50000 } as const;

export const BARSPLATES_FRAMES = {
  a: ["xpTrough", "toast", "slot", "slotSelected"],
  b: ["scrollTrack", "scrollThumb", "divider"],
} as const;

export type BarsplatesClip = keyof typeof BARSPLATES_FRAMES;
