// GENERATED by scripts/build_atlas.py -- do not edit by hand.
// Regenerate with: npm run assets

export const BOSSBAR_TEXTURE_KEY = "bossBar" as const;

/** How tall the character itself is inside the frame box, 0..1.
 *  Cells are padded by trails and motion range, so this -- not the frame
 *  height -- is what two characters must be compared on to size them
 *  relative to each other. */
export const BOSSBAR_BODY_RATIO = 0.98790 as const;

/** Every frame shares this source box, so one origin works for all of them. */
export const BOSSBAR_FRAME_SIZE = { width: 374, height: 62 } as const;

/** Origin on the body centre and its vertical centre. */
export const BOSSBAR_ANCHOR = { x: 0.50000, y: 0.50000 } as const;

export const BOSSBAR_FRAMES = {
  bar: ["bar"],
  divider: ["divider"],
} as const;

export type BossbarClip = keyof typeof BOSSBAR_FRAMES;
