// GENERATED by scripts/build_atlas.py -- do not edit by hand.
// Regenerate with: npm run assets

export const BRO_TEXTURE_KEY = "bro" as const;

/** How tall the character itself is inside the frame box, 0..1.
 *  Cells are padded by trails and motion range, so this -- not the frame
 *  height -- is what two characters must be compared on to size them
 *  relative to each other. */
export const BRO_BODY_RATIO = 0.56186 as const;

/** Every frame shares this source box, so one origin works for all of them. */
export const BRO_FRAME_SIZE = { width: 162, height: 194 } as const;

/** Origin on the body centre and its vertical centre. */
export const BRO_ANCHOR = { x: 0.49383, y: 0.45876 } as const;

export const BRO_FRAMES = {
  idle: ["idle-00", "idle-01", "idle-02", "idle-03", "idle-04", "idle-05", "idle-06", "idle-07"],
  hover: ["hover-00", "hover-01", "hover-02", "hover-03", "hover-04", "hover-05", "hover-06", "hover-07"],
  moveRight: ["moveRight-00", "moveRight-01", "moveRight-02", "moveRight-03", "moveRight-04", "moveRight-05", "moveRight-06", "moveRight-07"],
  moveLeft: ["moveLeft-00", "moveLeft-01", "moveLeft-02", "moveLeft-03", "moveLeft-04", "moveLeft-05", "moveLeft-06", "moveLeft-07"],
  moveUp: ["moveUp-00", "moveUp-01", "moveUp-02", "moveUp-03", "moveUp-04", "moveUp-05", "moveUp-06", "moveUp-07"],
  moveDown: ["moveDown-00", "moveDown-01", "moveDown-02", "moveDown-03", "moveDown-04", "moveDown-05", "moveDown-06", "moveDown-07"],
  danceHappy: ["danceHappy-00", "danceHappy-01", "danceHappy-02", "danceHappy-03", "danceHappy-04", "danceHappy-05", "danceHappy-06", "danceHappy-07", "danceHappy-08", "danceHappy-09", "danceHappy-10", "danceHappy-11"],
  danceSpin: ["danceSpin-00", "danceSpin-01", "danceSpin-02", "danceSpin-03", "danceSpin-04", "danceSpin-05", "danceSpin-06", "danceSpin-07", "danceSpin-08", "danceSpin-09"],
  surprised: ["surprised-00", "surprised-01", "surprised-02", "surprised-03", "surprised-04", "surprised-05"],
  lookAround: ["lookAround-00", "lookAround-01", "lookAround-02", "lookAround-03", "lookAround-04", "lookAround-05", "lookAround-06"],
  danceExcited: ["danceExcited-00", "danceExcited-01", "danceExcited-02", "danceExcited-03", "danceExcited-04", "danceExcited-05", "danceExcited-06", "danceExcited-07", "danceExcited-08", "danceExcited-09"],
} as const;

export type BroClip = keyof typeof BRO_FRAMES;
