// GENERATED by scripts/build_atlas.py -- do not edit by hand.
// Regenerate with: npm run assets

export const BRUTEATTACK_TEXTURE_KEY = "bruteAttack" as const;

/** How tall the character itself is inside the frame box, 0..1.
 *  Cells are padded by trails and motion range, so this -- not the frame
 *  height -- is what two characters must be compared on to size them
 *  relative to each other. */
export const BRUTEATTACK_BODY_RATIO = 0.93137 as const;

/** Every frame shares this source box, so one origin works for all of them. */
export const BRUTEATTACK_FRAME_SIZE = { width: 402, height: 408 } as const;

/** Origin on the body centre and its feet. */
export const BRUTEATTACK_ANCHOR = { x: 0.44279, y: 0.98529 } as const;

export const BRUTEATTACK_FRAMES = {
  a: ["f-00", "f-01", "f-02", "f-03"],
  b: ["f-04", "f-05", "f-06", "f-07"],
} as const;

export type BruteattackClip = keyof typeof BRUTEATTACK_FRAMES;
