// GENERATED by scripts/build_atlas.py -- do not edit by hand.
// Regenerate with: npm run assets

export const BRUTEALERT_TEXTURE_KEY = "bruteAlert" as const;

/** How tall the character itself is inside the frame box, 0..1.
 *  Cells are padded by trails and motion range, so this -- not the frame
 *  height -- is what two characters must be compared on to size them
 *  relative to each other. */
export const BRUTEALERT_BODY_RATIO = 0.77865 as const;

/** Every frame shares this source box, so one origin works for all of them. */
export const BRUTEALERT_FRAME_SIZE = { width: 379, height: 384 } as const;

/** Origin on the body centre and its feet. */
export const BRUTEALERT_ANCHOR = { x: 0.46174, y: 0.99740 } as const;

export const BRUTEALERT_FRAMES = {
  a: ["f-00", "f-01", "f-02", "f-03"],
  b: ["f-04", "f-05", "f-06", "f-07"],
} as const;

export type BrutealertClip = keyof typeof BRUTEALERT_FRAMES;
