// GENERATED by scripts/build_atlas.py -- do not edit by hand.
// Regenerate with: npm run assets

export const BUILDINGS_TEXTURE_KEY = "buildings" as const;

/** How tall the character itself is inside the frame box, 0..1.
 *  Cells are padded by trails and motion range, so this -- not the frame
 *  height -- is what two characters must be compared on to size them
 *  relative to each other. */
export const BUILDINGS_BODY_RATIO = 0.77083 as const;

/** Every frame shares this source box, so one origin works for all of them. */
export const BUILDINGS_FRAME_SIZE = { width: 248, height: 216 } as const;

/** Origin on the body centre and its feet. */
export const BUILDINGS_ANCHOR = { x: 0.43548, y: 0.99537 } as const;

export const BUILDINGS_FRAMES = {
  a: ["hut0", "hut1", "hut2", "forge0"],
  b: ["hutBig0", "hutBig1", "stall0", "banner0"],
} as const;

export type BuildingsClip = keyof typeof BUILDINGS_FRAMES;
