// GENERATED by scripts/build_atlas.py -- do not edit by hand.
// Regenerate with: npm run assets

export const CHEST_TEXTURE_KEY = "chest" as const;

/** How tall the character itself is inside the frame box, 0..1.
 *  Cells are padded by trails and motion range, so this -- not the frame
 *  height -- is what two characters must be compared on to size them
 *  relative to each other. */
export const CHEST_BODY_RATIO = 0.77201 as const;

/** Every frame shares this source box, so one origin works for all of them. */
export const CHEST_FRAME_SIZE = { width: 165, height: 159 } as const;

/** Origin on the body centre and its feet. */
export const CHEST_ANCHOR = { x: 0.49091, y: 0.99371 } as const;

export const CHEST_FRAMES = {
  a: ["chest0", "chest1", "chest2", "chest3"],
  b: ["chest4", "chest5", "chest6", "chest7"],
} as const;

export type ChestClip = keyof typeof CHEST_FRAMES;
