// GENERATED by scripts/build_atlas.py -- do not edit by hand.
// Regenerate with: npm run assets

export const CONTROLS_TEXTURE_KEY = "controls" as const;

/** How tall the character itself is inside the frame box, 0..1.
 *  Cells are padded by trails and motion range, so this -- not the frame
 *  height -- is what two characters must be compared on to size them
 *  relative to each other. */
export const CONTROLS_BODY_RATIO = 0.92029 as const;

/** Every frame shares this source box, so one origin works for all of them. */
export const CONTROLS_FRAME_SIZE = { width: 173, height: 69 } as const;

/** Origin on the body centre and its vertical centre. */
export const CONTROLS_ANCHOR = { x: 0.49711, y: 0.49275 } as const;

export const CONTROLS_FRAMES = {
  a: ["button", "buttonPress", "toggleOff", "toggleOn"],
  b: ["sliderTrack", "sliderKnob", "tab", "tabActive"],
} as const;

export type ControlsClip = keyof typeof CONTROLS_FRAMES;
