// GENERATED by scripts/build_atlas.py -- do not edit by hand.
// Regenerate with: npm run assets

export const CRYPTPROPS_TEXTURE_KEY = "cryptProps" as const;

/** How tall the character itself is inside the frame box, 0..1.
 *  Cells are padded by trails and motion range, so this -- not the frame
 *  height -- is what two characters must be compared on to size them
 *  relative to each other. */
export const CRYPTPROPS_BODY_RATIO = 0.57763 as const;

/** Every frame shares this source box, so one origin works for all of them. */
export const CRYPTPROPS_FRAME_SIZE = { width: 168, height: 219 } as const;

/** Origin on the body centre and its feet. */
export const CRYPTPROPS_ANCHOR = { x: 0.50595, y: 1.00000 } as const;

export const CRYPTPROPS_FRAMES = {
  a: ["bonePile0", "skullStack0", "cobweb0", "hangingChain0"],
  b: ["coffinCracked0", "candleCluster0", "ironCage0", "rootIntrusion0"],
} as const;

export type CryptpropsClip = keyof typeof CRYPTPROPS_FRAMES;
