// GENERATED by scripts/build_atlas.py -- do not edit by hand.
// Regenerate with: npm run assets

export const DUMMY_TEXTURE_KEY = "dummy" as const;

/** How tall the character itself is inside the frame box, 0..1.
 *  Cells are padded by trails and motion range, so this -- not the frame
 *  height -- is what two characters must be compared on to size them
 *  relative to each other. */
export const DUMMY_BODY_RATIO = 0.95150 as const;

/** Every frame shares this source box, so one origin works for all of them. */
export const DUMMY_FRAME_SIZE = { width: 330, height: 433 } as const;

/** Origin on the body centre and its feet. */
export const DUMMY_ANCHOR = { x: 0.46061, y: 1.00000 } as const;

export const DUMMY_FRAMES = {
  hit: ["hit-00", "hit-01", "hit-02", "hit-03"],
  hit_b: ["hit-04", "hit-05", "hit-06", "hit-07"],
} as const;

export type DummyClip = keyof typeof DUMMY_FRAMES;
