// GENERATED by scripts/build_atlas.py -- do not edit by hand.
// Regenerate with: npm run assets

export const FIREPILLAR_TEXTURE_KEY = "firePillar" as const;

/** How tall the character itself is inside the frame box, 0..1.
 *  Cells are padded by trails and motion range, so this -- not the frame
 *  height -- is what two characters must be compared on to size them
 *  relative to each other. */
export const FIREPILLAR_BODY_RATIO = 0.82966 as const;

/** Every frame shares this source box, so one origin works for all of them. */
export const FIREPILLAR_FRAME_SIZE = { width: 334, height: 499 } as const;

/** Origin on the body centre and its vertical centre. */
export const FIREPILLAR_ANCHOR = { x: 0.59581, y: 0.49900 } as const;

export const FIREPILLAR_FRAMES = {
  cast: ["cast-00", "cast-01", "cast-02", "cast-03"],
  cast_b: ["cast-04", "cast-05", "cast-06", "cast-07"],
} as const;

export type FirepillarClip = keyof typeof FIREPILLAR_FRAMES;
