// GENERATED by scripts/build_atlas.py -- do not edit by hand.
// Regenerate with: npm run assets

export const FIREWAVE_TEXTURE_KEY = "fireWave" as const;

/** How tall the character itself is inside the frame box, 0..1.
 *  Cells are padded by trails and motion range, so this -- not the frame
 *  height -- is what two characters must be compared on to size them
 *  relative to each other. */
export const FIREWAVE_BODY_RATIO = 0.70690 as const;

/** Every frame shares this source box, so one origin works for all of them. */
export const FIREWAVE_FRAME_SIZE = { width: 366, height: 232 } as const;

/** Origin on the body centre and its vertical centre. */
export const FIREWAVE_ANCHOR = { x: 0.50546, y: 0.49569 } as const;

export const FIREWAVE_FRAMES = {
  cast: ["cast-00", "cast-01", "cast-02", "cast-03"],
  cast_b: ["cast-04", "cast-05", "cast-06", "cast-07"],
} as const;

export type FirewaveClip = keyof typeof FIREWAVE_FRAMES;
