// GENERATED by scripts/build_atlas.py -- do not edit by hand.
// Regenerate with: npm run assets

export const FIRESTAFFIDLE_TEXTURE_KEY = "fireStaffIdle" as const;

/** How tall the character itself is inside the frame box, 0..1.
 *  Cells are padded by trails and motion range, so this -- not the frame
 *  height -- is what two characters must be compared on to size them
 *  relative to each other. */
export const FIRESTAFFIDLE_BODY_RATIO = 0.96178 as const;

/** Every frame shares this source box, so one origin works for all of them. */
export const FIRESTAFFIDLE_FRAME_SIZE = { width: 133, height: 471 } as const;

/** Origin on the body centre and its vertical centre. */
export const FIRESTAFFIDLE_ANCHOR = { x: 0.48872, y: 0.46921 } as const;

export const FIRESTAFFIDLE_FRAMES = {
  swing: ["swing-00", "swing-01", "swing-02", "swing-03"],
  swing_b: ["swing-04", "swing-05", "swing-06", "swing-07"],
} as const;

export type FirestaffidleClip = keyof typeof FIRESTAFFIDLE_FRAMES;
