// GENERATED by scripts/build_atlas.py -- do not edit by hand.
// Regenerate with: npm run assets

export const FLOURISHES_TEXTURE_KEY = "flourishes" as const;

/** How tall the character itself is inside the frame box, 0..1.
 *  Cells are padded by trails and motion range, so this -- not the frame
 *  height -- is what two characters must be compared on to size them
 *  relative to each other. */
export const FLOURISHES_BODY_RATIO = 0.95213 as const;

/** Every frame shares this source box, so one origin works for all of them. */
export const FLOURISHES_FRAME_SIZE = { width: 193, height: 188 } as const;

/** Origin on the body centre and its vertical centre. */
export const FLOURISHES_ANCHOR = { x: 0.39378, y: 0.50000 } as const;

export const FLOURISHES_FRAMES = {
  mark: ["death", "victory", "levelUp"],
} as const;

export type FlourishesClip = keyof typeof FLOURISHES_FRAMES;
