// GENERATED by scripts/build_atlas.py -- do not edit by hand.
// Regenerate with: npm run assets

export const GLYPHS_TEXTURE_KEY = "glyphs" as const;

/** How tall the character itself is inside the frame box, 0..1.
 *  Cells are padded by trails and motion range, so this -- not the frame
 *  height -- is what two characters must be compared on to size them
 *  relative to each other. */
export const GLYPHS_BODY_RATIO = 0.83494 as const;

/** Every frame shares this source box, so one origin works for all of them. */
export const GLYPHS_FRAME_SIZE = { width: 79, height: 78 } as const;

/** Origin on the body centre and its vertical centre. */
export const GLYPHS_ANCHOR = { x: 0.49367, y: 0.50000 } as const;

export const GLYPHS_FRAMES = {
  a: ["close", "back", "confirm", "plus"],
  b: ["minus", "locked", "warning", "info"],
} as const;

export type GlyphsClip = keyof typeof GLYPHS_FRAMES;
