// GENERATED by scripts/build_atlas.py -- do not edit by hand.
// Regenerate with: npm run assets

export const GOAT_TEXTURE_KEY = "goat" as const;

/** How tall the character itself is inside the frame box, 0..1.
 *  Cells are padded by trails and motion range, so this -- not the frame
 *  height -- is what two characters must be compared on to size them
 *  relative to each other. */
export const GOAT_BODY_RATIO = 0.74048 as const;

/** Every frame shares this source box, so one origin works for all of them. */
export const GOAT_FRAME_SIZE = { width: 251, height: 289 } as const;

/** Origin on the body centre and its feet. */
export const GOAT_ANCHOR = { x: 0.45817, y: 0.92388 } as const;

export const GOAT_FRAMES = {
  idle: ["idle-00", "idle-01", "idle-02", "idle-03", "idle-04", "idle-05"],
  walk: ["walk-00", "walk-01", "walk-02", "walk-03", "walk-04", "walk-05"],
  run: ["run-00", "run-01", "run-02", "run-03", "run-04"],
  jump: ["jump-00", "jump-01", "jump-02", "jump-03", "jump-04", "jump-05"],
  strike: ["strike-00", "strike-01", "strike-02", "strike-03", "strike-04", "strike-05"],
  attack: ["attack-00", "attack-01", "attack-02", "attack-03", "attack-04", "attack-05"],
  swirl: ["swirl-02", "swirl-03", "swirl-04", "swirl-05"],
  hurt: ["hurt-00"],
  die: ["die-00"],
  face: ["face-normal", "face-happy", "face-excited", "face-angry", "face-sad", "face-surprised", "face-confused", "face-sleepy", "face-wink", "face-blush"],
} as const;

export type GoatClip = keyof typeof GOAT_FRAMES;
