// GENERATED by scripts/build_atlas.py -- do not edit by hand.
// Regenerate with: npm run assets

export const GROVEPROPS_TEXTURE_KEY = "groveProps" as const;

/** How tall the character itself is inside the frame box, 0..1.
 *  Cells are padded by trails and motion range, so this -- not the frame
 *  height -- is what two characters must be compared on to size them
 *  relative to each other. */
export const GROVEPROPS_BODY_RATIO = 0.54867 as const;

/** Every frame shares this source box, so one origin works for all of them. */
export const GROVEPROPS_FRAME_SIZE = { width: 181, height: 226 } as const;

/** Origin on the body centre and its feet. */
export const GROVEPROPS_ANCHOR = { x: 0.46961, y: 1.00000 } as const;

export const GROVEPROPS_FRAMES = {
  a: ["fallenTrunk0", "stump0", "berryBush0", "reeds0"],
  b: ["fernClump0", "mossRock0", "fencePost0", "cartWheel0"],
} as const;

export type GrovepropsClip = keyof typeof GROVEPROPS_FRAMES;
