// GENERATED by scripts/build_atlas.py -- do not edit by hand.
// Regenerate with: npm run assets

export const HATCHCRACK_TEXTURE_KEY = "hatchCrack" as const;

/** How tall the character itself is inside the frame box, 0..1.
 *  Cells are padded by trails and motion range, so this -- not the frame
 *  height -- is what two characters must be compared on to size them
 *  relative to each other. */
export const HATCHCRACK_BODY_RATIO = 0.75000 as const;

/** Every frame shares this source box, so one origin works for all of them. */
export const HATCHCRACK_FRAME_SIZE = { width: 350, height: 396 } as const;

/** Origin on the body centre and its vertical centre. */
export const HATCHCRACK_ANCHOR = { x: 0.51143, y: 0.48990 } as const;

export const HATCHCRACK_FRAMES = {
  a: ["f-00", "f-01", "f-02", "f-03"],
  b: ["f-04", "f-05", "f-06", "f-07"],
} as const;

export type HatchcrackClip = keyof typeof HATCHCRACK_FRAMES;
