// GENERATED by scripts/build_atlas.py -- do not edit by hand.
// Regenerate with: npm run assets

export const HOTBAR_TEXTURE_KEY = "hotbar" as const;

/** How tall the character itself is inside the frame box, 0..1.
 *  Cells are padded by trails and motion range, so this -- not the frame
 *  height -- is what two characters must be compared on to size them
 *  relative to each other. */
export const HOTBAR_BODY_RATIO = 0.99398 as const;

/** Every frame shares this source box, so one origin works for all of them. */
export const HOTBAR_FRAME_SIZE = { width: 739, height: 249 } as const;

/** Origin on the body centre and its vertical centre. */
export const HOTBAR_ANCHOR = { x: 0.49932, y: 0.49799 } as const;

export const HOTBAR_FRAMES = {
  plate: ["plate"],
} as const;

export type HotbarClip = keyof typeof HOTBAR_FRAMES;
