// GENERATED by scripts/build_atlas.py -- do not edit by hand.
// Regenerate with: npm run assets

export const ICEBEAMCASTDARK_TEXTURE_KEY = "iceBeamCastDark" as const;

/** How tall the character itself is inside the frame box, 0..1.
 *  Cells are padded by trails and motion range, so this -- not the frame
 *  height -- is what two characters must be compared on to size them
 *  relative to each other. */
export const ICEBEAMCASTDARK_BODY_RATIO = 0.61951 as const;

/** Every frame shares this source box, so one origin works for all of them. */
export const ICEBEAMCASTDARK_FRAME_SIZE = { width: 406, height: 410 } as const;

/** Origin on the body centre and its vertical centre. */
export const ICEBEAMCASTDARK_ANCHOR = { x: 0.41379, y: 0.53659 } as const;

export const ICEBEAMCASTDARK_FRAMES = {
  swing: ["swing-00", "swing-01", "swing-02", "swing-03"],
  swing_b: ["swing-04", "swing-05", "swing-06", "swing-07"],
} as const;

export type IcebeamcastdarkClip = keyof typeof ICEBEAMCASTDARK_FRAMES;
