// GENERATED by scripts/build_atlas.py -- do not edit by hand.
// Regenerate with: npm run assets

export const ICENOVACAST_TEXTURE_KEY = "iceNovaCast" as const;

/** How tall the character itself is inside the frame box, 0..1.
 *  Cells are padded by trails and motion range, so this -- not the frame
 *  height -- is what two characters must be compared on to size them
 *  relative to each other. */
export const ICENOVACAST_BODY_RATIO = 0.82647 as const;

/** Every frame shares this source box, so one origin works for all of them. */
export const ICENOVACAST_FRAME_SIZE = { width: 399, height: 510 } as const;

/** Origin on the body centre and its vertical centre. */
export const ICENOVACAST_ANCHOR = { x: 0.51378, y: 0.41765 } as const;

export const ICENOVACAST_FRAMES = {
  swing: ["swing-00", "swing-01", "swing-02", "swing-03"],
  swing_b: ["swing-04", "swing-05", "swing-06", "swing-07"],
} as const;

export type IcenovacastClip = keyof typeof ICENOVACAST_FRAMES;
