// GENERATED by scripts/build_atlas.py -- do not edit by hand.
// Regenerate with: npm run assets

export const ICENOVADARK_TEXTURE_KEY = "iceNovaDark" as const;

/** How tall the character itself is inside the frame box, 0..1.
 *  Cells are padded by trails and motion range, so this -- not the frame
 *  height -- is what two characters must be compared on to size them
 *  relative to each other. */
export const ICENOVADARK_BODY_RATIO = 0.58696 as const;

/** Every frame shares this source box, so one origin works for all of them. */
export const ICENOVADARK_FRAME_SIZE = { width: 435, height: 322 } as const;

/** Origin on the body centre and its vertical centre. */
export const ICENOVADARK_ANCHOR = { x: 0.56322, y: 0.50000 } as const;

export const ICENOVADARK_FRAMES = {
  cast: ["cast-00", "cast-01", "cast-02", "cast-03"],
  cast_b: ["cast-04", "cast-05", "cast-06", "cast-07"],
} as const;

export type IcenovadarkClip = keyof typeof ICENOVADARK_FRAMES;
