// GENERATED by scripts/build_atlas.py -- do not edit by hand.
// Regenerate with: npm run assets

export const ICONS_TEXTURE_KEY = "icons" as const;

/** How tall the character itself is inside the frame box, 0..1.
 *  Cells are padded by trails and motion range, so this -- not the frame
 *  height -- is what two characters must be compared on to size them
 *  relative to each other. */
export const ICONS_BODY_RATIO = 0.76337 as const;

/** Every frame shares this source box, so one origin works for all of them. */
export const ICONS_FRAME_SIZE = { width: 128, height: 128 } as const;

/** Origin on the body centre and its vertical centre. */
export const ICONS_ANCHOR = { x: 0.49219, y: 0.50000 } as const;

export const ICONS_FRAMES = {
  icon: ["fireBall", "firePillar", "fireWave", "arrow"],
  icon_b: ["iceNova", "iceShards", "iceBeam", "sword"],
} as const;

export type IconsClip = keyof typeof ICONS_FRAMES;
