// GENERATED by scripts/build_atlas.py -- do not edit by hand.
// Regenerate with: npm run assets

export const ITEMS_TEXTURE_KEY = "items" as const;

/** How tall the character itself is inside the frame box, 0..1.
 *  Cells are padded by trails and motion range, so this -- not the frame
 *  height -- is what two characters must be compared on to size them
 *  relative to each other. */
export const ITEMS_BODY_RATIO = 0.85644 as const;

/** Every frame shares this source box, so one origin works for all of them. */
export const ITEMS_FRAME_SIZE = { width: 80, height: 101 } as const;

/** Origin on the body centre and its vertical centre. */
export const ITEMS_ANCHOR = { x: 0.51250, y: 0.49505 } as const;

export const ITEMS_FRAMES = {
  item: ["health_potion", "mana_potion", "ember_heart", "wolf_fang"],
  item_b: ["mirror_eye", "essence", "shards"],
} as const;

export type ItemsClip = keyof typeof ITEMS_FRAMES;
