// GENERATED by scripts/build_atlas.py -- do not edit by hand.
// Regenerate with: npm run assets

export const MAPTOKENS_TEXTURE_KEY = "mapTokens" as const;

/** How tall the character itself is inside the frame box, 0..1.
 *  Cells are padded by trails and motion range, so this -- not the frame
 *  height -- is what two characters must be compared on to size them
 *  relative to each other. */
export const MAPTOKENS_BODY_RATIO = 0.98889 as const;

/** Every frame shares this source box, so one origin works for all of them. */
export const MAPTOKENS_FRAME_SIZE = { width: 156, height: 135 } as const;

/** Origin on the body centre and its vertical centre. */
export const MAPTOKENS_ANCHOR = { x: 0.50000, y: 0.49630 } as const;

export const MAPTOKENS_FRAMES = {
  a: ["roomUnvisited", "roomVisited", "roomCleared", "roomCurrent"],
  b: ["treasure", "elite", "boss", "corridor"],
} as const;

export type MaptokensClip = keyof typeof MAPTOKENS_FRAMES;
