// GENERATED by scripts/build_atlas.py -- do not edit by hand.
// Regenerate with: npm run assets

export const MINIMAPRING_TEXTURE_KEY = "minimapRing" as const;

/** How tall the character itself is inside the frame box, 0..1.
 *  Cells are padded by trails and motion range, so this -- not the frame
 *  height -- is what two characters must be compared on to size them
 *  relative to each other. */
export const MINIMAPRING_BODY_RATIO = 0.99581 as const;

/** Every frame shares this source box, so one origin works for all of them. */
export const MINIMAPRING_FRAME_SIZE = { width: 301, height: 298 } as const;

/** Origin on the body centre and its vertical centre. */
export const MINIMAPRING_ANCHOR = { x: 0.49834, y: 0.50000 } as const;

export const MINIMAPRING_FRAMES = {
  ring: ["ring"],
} as const;

export type MinimapringClip = keyof typeof MINIMAPRING_FRAMES;
