// GENERATED by scripts/build_atlas.py -- do not edit by hand.
// Regenerate with: npm run assets

export const MIRRORCAST_TEXTURE_KEY = "mirrorCast" as const;

/** How tall the character itself is inside the frame box, 0..1.
 *  Cells are padded by trails and motion range, so this -- not the frame
 *  height -- is what two characters must be compared on to size them
 *  relative to each other. */
export const MIRRORCAST_BODY_RATIO = 0.87921 as const;

/** Every frame shares this source box, so one origin works for all of them. */
export const MIRRORCAST_FRAME_SIZE = { width: 374, height: 505 } as const;

/** Origin on the body centre and its vertical centre. */
export const MIRRORCAST_ANCHOR = { x: 0.50267, y: 0.50099 } as const;

export const MIRRORCAST_FRAMES = {
  a: ["f-00", "f-01", "f-02", "f-03"],
  b: ["f-04", "f-05", "f-06", "f-07"],
} as const;

export type MirrorcastClip = keyof typeof MIRRORCAST_FRAMES;
