// GENERATED by scripts/build_atlas.py -- do not edit by hand.
// Regenerate with: npm run assets

export const MIRRORHURT_TEXTURE_KEY = "mirrorHurt" as const;

/** How tall the character itself is inside the frame box, 0..1.
 *  Cells are padded by trails and motion range, so this -- not the frame
 *  height -- is what two characters must be compared on to size them
 *  relative to each other. */
export const MIRRORHURT_BODY_RATIO = 0.88229 as const;

/** Every frame shares this source box, so one origin works for all of them. */
export const MIRRORHURT_FRAME_SIZE = { width: 361, height: 497 } as const;

/** Origin on the body centre and its vertical centre. */
export const MIRRORHURT_ANCHOR = { x: 0.49307, y: 0.49899 } as const;

export const MIRRORHURT_FRAMES = {
  a: ["f-00", "f-01", "f-02", "f-03"],
  b: ["f-04", "f-05", "f-06", "f-07"],
} as const;

export type MirrorhurtClip = keyof typeof MIRRORHURT_FRAMES;
