// GENERATED by scripts/build_atlas.py -- do not edit by hand.
// Regenerate with: npm run assets

export const MIRRORDRIFT_TEXTURE_KEY = "mirrorDrift" as const;

/** How tall the character itself is inside the frame box, 0..1.
 *  Cells are padded by trails and motion range, so this -- not the frame
 *  height -- is what two characters must be compared on to size them
 *  relative to each other. */
export const MIRRORDRIFT_BODY_RATIO = 0.93869 as const;

/** Every frame shares this source box, so one origin works for all of them. */
export const MIRRORDRIFT_FRAME_SIZE = { width: 377, height: 473 } as const;

/** Origin on the body centre and its vertical centre. */
export const MIRRORDRIFT_ANCHOR = { x: 0.49867, y: 0.49683 } as const;

export const MIRRORDRIFT_FRAMES = {
  a: ["f-00", "f-01", "f-02", "f-03"],
  b: ["f-04", "f-05", "f-06", "f-07"],
} as const;

export type MirrordriftClip = keyof typeof MIRRORDRIFT_FRAMES;
