// GENERATED by scripts/build_atlas.py -- do not edit by hand.
// Regenerate with: npm run assets

export const MIRRORDEATH_TEXTURE_KEY = "mirrorDeath" as const;

/** How tall the character itself is inside the frame box, 0..1.
 *  Cells are padded by trails and motion range, so this -- not the frame
 *  height -- is what two characters must be compared on to size them
 *  relative to each other. */
export const MIRRORDEATH_BODY_RATIO = 0.96377 as const;

/** Every frame shares this source box, so one origin works for all of them. */
export const MIRRORDEATH_FRAME_SIZE = { width: 358, height: 483 } as const;

/** Origin on the body centre and its vertical centre. */
export const MIRRORDEATH_ANCHOR = { x: 0.49441, y: 0.49896 } as const;

export const MIRRORDEATH_FRAMES = {
  a: ["f-00", "f-01", "f-02", "f-03"],
  b: ["f-04", "f-05", "f-06", "f-07"],
} as const;

export type MirrordeathClip = keyof typeof MIRRORDEATH_FRAMES;
