// GENERATED by scripts/build_atlas.py -- do not edit by hand.
// Regenerate with: npm run assets

export const POTIONDIAL_TEXTURE_KEY = "potionDial" as const;

/** How tall the character itself is inside the frame box, 0..1.
 *  Cells are padded by trails and motion range, so this -- not the frame
 *  height -- is what two characters must be compared on to size them
 *  relative to each other. */
export const POTIONDIAL_BODY_RATIO = 0.99425 as const;

/** Every frame shares this source box, so one origin works for all of them. */
export const POTIONDIAL_FRAME_SIZE = { width: 266, height: 261 } as const;

/** Origin on the body centre and its vertical centre. */
export const POTIONDIAL_ANCHOR = { x: 0.50000, y: 0.49808 } as const;

export const POTIONDIAL_FRAMES = {
  dial: ["dial"],
} as const;

export type PotiondialClip = keyof typeof POTIONDIAL_FRAMES;
