// GENERATED by scripts/build_atlas.py -- do not edit by hand.
// Regenerate with: npm run assets

export const RUINSPROPS_TEXTURE_KEY = "ruinsProps" as const;

/** How tall the character itself is inside the frame box, 0..1.
 *  Cells are padded by trails and motion range, so this -- not the frame
 *  height -- is what two characters must be compared on to size them
 *  relative to each other. */
export const RUINSPROPS_BODY_RATIO = 0.58374 as const;

/** Every frame shares this source box, so one origin works for all of them. */
export const RUINSPROPS_FRAME_SIZE = { width: 181, height: 206 } as const;

/** Origin on the body centre and its feet. */
export const RUINSPROPS_ANCHOR = { x: 0.51934, y: 0.99515 } as const;

export const RUINSPROPS_FRAMES = {
  a: ["archBroken0", "columnFallen0", "stoneBench0", "urnCracked0"],
  b: ["stairFragment0", "runeStone0", "sarcophagus0", "banneredRubble0"],
} as const;

export type RuinspropsClip = keyof typeof RUINSPROPS_FRAMES;
