// GENERATED by scripts/build_atlas.py -- do not edit by hand.
// Regenerate with: npm run assets

export const SCREENFRAME_TEXTURE_KEY = "screenFrame" as const;

/** How tall the character itself is inside the frame box, 0..1.
 *  Cells are padded by trails and motion range, so this -- not the frame
 *  height -- is what two characters must be compared on to size them
 *  relative to each other. */
export const SCREENFRAME_BODY_RATIO = 1.00099 as const;

/** Every frame shares this source box, so one origin works for all of them. */
export const SCREENFRAME_FRAME_SIZE = { width: 506, height: 506 } as const;

/** Origin on the body centre and its vertical centre. */
export const SCREENFRAME_ANCHOR = { x: 0.50000, y: 0.50000 } as const;

export const SCREENFRAME_FRAMES = {
  frame: ["frame"],
} as const;

export type ScreenframeClip = keyof typeof SCREENFRAME_FRAMES;
