// GENERATED by scripts/build_atlas.py -- do not edit by hand.
// Regenerate with: npm run assets

export const SHARDRING_TEXTURE_KEY = "shardRing" as const;

/** How tall the character itself is inside the frame box, 0..1.
 *  Cells are padded by trails and motion range, so this -- not the frame
 *  height -- is what two characters must be compared on to size them
 *  relative to each other. */
export const SHARDRING_BODY_RATIO = 0.63333 as const;

/** Every frame shares this source box, so one origin works for all of them. */
export const SHARDRING_FRAME_SIZE = { width: 437, height: 270 } as const;

/** Origin on the body centre and its vertical centre. */
export const SHARDRING_ANCHOR = { x: 0.49657, y: 0.50000 } as const;

export const SHARDRING_FRAMES = {
  cast: ["cast-00", "cast-01", "cast-02", "cast-03"],
  cast_b: ["cast-04", "cast-05", "cast-06", "cast-07"],
} as const;

export type ShardringClip = keyof typeof SHARDRING_FRAMES;
