// GENERATED by scripts/build_atlas.py -- do not edit by hand.
// Regenerate with: npm run assets

export const SHARDLINGWALK_TEXTURE_KEY = "shardlingWalk" as const;

/** How tall the character itself is inside the frame box, 0..1.
 *  Cells are padded by trails and motion range, so this -- not the frame
 *  height -- is what two characters must be compared on to size them
 *  relative to each other. */
export const SHARDLINGWALK_BODY_RATIO = 0.94694 as const;

/** Every frame shares this source box, so one origin works for all of them. */
export const SHARDLINGWALK_FRAME_SIZE = { width: 367, height: 245 } as const;

/** Origin on the body centre and its feet. */
export const SHARDLINGWALK_ANCHOR = { x: 0.50409, y: 0.98776 } as const;

export const SHARDLINGWALK_FRAMES = {
  a: ["f-00", "f-01", "f-02", "f-03"],
  b: ["f-04", "f-05", "f-06", "f-07"],
} as const;

export type ShardlingwalkClip = keyof typeof SHARDLINGWALK_FRAMES;
