// GENERATED by scripts/build_atlas.py -- do not edit by hand.
// Regenerate with: npm run assets

export const SHIELDBLOCK_TEXTURE_KEY = "shieldBlock" as const;

/** How tall the character itself is inside the frame box, 0..1.
 *  Cells are padded by trails and motion range, so this -- not the frame
 *  height -- is what two characters must be compared on to size them
 *  relative to each other. */
export const SHIELDBLOCK_BODY_RATIO = 0.88571 as const;

/** Every frame shares this source box, so one origin works for all of them. */
export const SHIELDBLOCK_FRAME_SIZE = { width: 229, height: 350 } as const;

/** Origin on the body centre and its vertical centre. */
export const SHIELDBLOCK_ANCHOR = { x: 0.45415, y: 0.48857 } as const;

export const SHIELDBLOCK_FRAMES = {
  block: ["block-00", "block-01", "block-02", "block-03"],
  block_b: ["block-04", "block-05", "block-06", "block-07"],
} as const;

export type ShieldblockClip = keyof typeof SHIELDBLOCK_FRAMES;
