// GENERATED by scripts/build_atlas.py -- do not edit by hand.
// Regenerate with: npm run assets

export const SHIELDPARRYDARK_TEXTURE_KEY = "shieldParryDark" as const;

/** How tall the character itself is inside the frame box, 0..1.
 *  Cells are padded by trails and motion range, so this -- not the frame
 *  height -- is what two characters must be compared on to size them
 *  relative to each other. */
export const SHIELDPARRYDARK_BODY_RATIO = 0.85988 as const;

/** Every frame shares this source box, so one origin works for all of them. */
export const SHIELDPARRYDARK_FRAME_SIZE = { width: 330, height: 339 } as const;

/** Origin on the body centre and its vertical centre. */
export const SHIELDPARRYDARK_ANCHOR = { x: 0.41818, y: 0.48673 } as const;

export const SHIELDPARRYDARK_FRAMES = {
  parry: ["parry-00", "parry-01", "parry-02", "parry-03"],
  parry_b: ["parry-04", "parry-05", "parry-06", "parry-07"],
} as const;

export type ShieldparrydarkClip = keyof typeof SHIELDPARRYDARK_FRAMES;
