// GENERATED by scripts/build_atlas.py -- do not edit by hand.
// Regenerate with: npm run assets

export const SKELETONATTACK_TEXTURE_KEY = "skeletonAttack" as const;

/** How tall the character itself is inside the frame box, 0..1.
 *  Cells are padded by trails and motion range, so this -- not the frame
 *  height -- is what two characters must be compared on to size them
 *  relative to each other. */
export const SKELETONATTACK_BODY_RATIO = 0.94675 as const;

/** Every frame shares this source box, so one origin works for all of them. */
export const SKELETONATTACK_FRAME_SIZE = { width: 454, height: 385 } as const;

/** Origin on the body centre and its feet. */
export const SKELETONATTACK_ANCHOR = { x: 0.47577, y: 0.99221 } as const;

export const SKELETONATTACK_FRAMES = {
  a: ["f-00", "f-01", "f-02", "f-03"],
  b: ["f-04", "f-05", "f-06", "f-07"],
} as const;

export type SkeletonattackClip = keyof typeof SKELETONATTACK_FRAMES;
