// GENERATED by scripts/build_atlas.py -- do not edit by hand.
// Regenerate with: npm run assets

export const SKILLNODES_TEXTURE_KEY = "skillNodes" as const;

/** How tall the character itself is inside the frame box, 0..1.
 *  Cells are padded by trails and motion range, so this -- not the frame
 *  height -- is what two characters must be compared on to size them
 *  relative to each other. */
export const SKILLNODES_BODY_RATIO = 0.76214 as const;

/** Every frame shares this source box, so one origin works for all of them. */
export const SKILLNODES_FRAME_SIZE = { width: 193, height: 206 } as const;

/** Origin on the body centre and its vertical centre. */
export const SKILLNODES_ANCHOR = { x: 0.51295, y: 0.50000 } as const;

export const SKILLNODES_FRAMES = {
  node: ["locked", "available", "unlocked", "maxed"],
  emblem: ["combat", "magic", "mobility", "survival"],
} as const;

export type SkillnodesClip = keyof typeof SKILLNODES_FRAMES;
