// GENERATED by scripts/build_atlas.py -- do not edit by hand.
// Regenerate with: npm run assets

export const SLIMEALERT_TEXTURE_KEY = "slimeAlert" as const;

/** How tall the character itself is inside the frame box, 0..1.
 *  Cells are padded by trails and motion range, so this -- not the frame
 *  height -- is what two characters must be compared on to size them
 *  relative to each other. */
export const SLIMEALERT_BODY_RATIO = 0.80116 as const;

/** Every frame shares this source box, so one origin works for all of them. */
export const SLIMEALERT_FRAME_SIZE = { width: 410, height: 259 } as const;

/** Origin on the body centre and its feet. */
export const SLIMEALERT_ANCHOR = { x: 0.52927, y: 0.99614 } as const;

export const SLIMEALERT_FRAMES = {
  a: ["f-00", "f-01", "f-02", "f-03"],
  b: ["f-04", "f-05", "f-06", "f-07"],
} as const;

export type SlimealertClip = keyof typeof SLIMEALERT_FRAMES;
