// GENERATED by scripts/build_atlas.py -- do not edit by hand.
// Regenerate with: npm run assets

export const SPEAKERS_TEXTURE_KEY = "speakers" as const;

/** How tall the character itself is inside the frame box, 0..1.
 *  Cells are padded by trails and motion range, so this -- not the frame
 *  height -- is what two characters must be compared on to size them
 *  relative to each other. */
export const SPEAKERS_BODY_RATIO = 0.86991 as const;

/** Every frame shares this source box, so one origin works for all of them. */
export const SPEAKERS_FRAME_SIZE = { width: 201, height: 221 } as const;

/** Origin on the body centre and its vertical centre. */
export const SPEAKERS_ANCHOR = { x: 0.52239, y: 0.49774 } as const;

export const SPEAKERS_FRAMES = {
  a: ["elder_mara", "smith_oren", "apothecary_siv", "hearth"],
  b: ["twin", "villager"],
} as const;

export type SpeakersClip = keyof typeof SPEAKERS_FRAMES;
