// GENERATED by scripts/build_atlas.py -- do not edit by hand.
// Regenerate with: npm run assets

export const SPITTERIDLE_TEXTURE_KEY = "spitterIdle" as const;

/** How tall the character itself is inside the frame box, 0..1.
 *  Cells are padded by trails and motion range, so this -- not the frame
 *  height -- is what two characters must be compared on to size them
 *  relative to each other. */
export const SPITTERIDLE_BODY_RATIO = 0.97053 as const;

/** Every frame shares this source box, so one origin works for all of them. */
export const SPITTERIDLE_FRAME_SIZE = { width: 299, height: 475 } as const;

/** Origin on the body centre and its feet. */
export const SPITTERIDLE_ANCHOR = { x: 0.51171, y: 0.99158 } as const;

export const SPITTERIDLE_FRAMES = {
  a: ["f-00", "f-01", "f-02", "f-03"],
  b: ["f-04", "f-05", "f-06", "f-07"],
} as const;

export type SpitteridleClip = keyof typeof SPITTERIDLE_FRAMES;
