// GENERATED by scripts/build_atlas.py -- do not edit by hand.
// Regenerate with: npm run assets

export const SPITTERALERT_TEXTURE_KEY = "spitterAlert" as const;

/** How tall the character itself is inside the frame box, 0..1.
 *  Cells are padded by trails and motion range, so this -- not the frame
 *  height -- is what two characters must be compared on to size them
 *  relative to each other. */
export const SPITTERALERT_BODY_RATIO = 0.92402 as const;

/** Every frame shares this source box, so one origin works for all of them. */
export const SPITTERALERT_FRAME_SIZE = { width: 282, height: 487 } as const;

/** Origin on the body centre and its feet. */
export const SPITTERALERT_ANCHOR = { x: 0.53546, y: 0.98973 } as const;

export const SPITTERALERT_FRAMES = {
  a: ["f-00", "f-01", "f-02", "f-03"],
  b: ["f-04", "f-05", "f-06", "f-07"],
} as const;

export type SpitteralertClip = keyof typeof SPITTERALERT_FRAMES;
