// GENERATED by scripts/build_atlas.py -- do not edit by hand.
// Regenerate with: npm run assets

export const STATUSBARS_TEXTURE_KEY = "statusBars" as const;

/** How tall the character itself is inside the frame box, 0..1.
 *  Cells are padded by trails and motion range, so this -- not the frame
 *  height -- is what two characters must be compared on to size them
 *  relative to each other. */
export const STATUSBARS_BODY_RATIO = 0.97917 as const;

/** Every frame shares this source box, so one origin works for all of them. */
export const STATUSBARS_FRAME_SIZE = { width: 363, height: 48 } as const;

/** Origin on the body centre and its vertical centre. */
export const STATUSBARS_ANCHOR = { x: 0.49862, y: 0.50000 } as const;

export const STATUSBARS_FRAMES = {
  hp: ["hp"],
  mp: ["mp"],
} as const;

export type StatusbarsClip = keyof typeof STATUSBARS_FRAMES;
