// GENERATED by scripts/build_atlas.py -- do not edit by hand.
// Regenerate with: npm run assets

export const SWORDIDLEDARK_TEXTURE_KEY = "swordIdleDark" as const;

/** How tall the character itself is inside the frame box, 0..1.
 *  Cells are padded by trails and motion range, so this -- not the frame
 *  height -- is what two characters must be compared on to size them
 *  relative to each other. */
export const SWORDIDLEDARK_BODY_RATIO = 0.87002 as const;

/** Every frame shares this source box, so one origin works for all of them. */
export const SWORDIDLEDARK_FRAME_SIZE = { width: 152, height: 527 } as const;

/** Origin on the body centre and its vertical centre. */
export const SWORDIDLEDARK_ANCHOR = { x: 0.51316, y: 0.58065 } as const;

export const SWORDIDLEDARK_FRAMES = {
  swing: ["swing-00", "swing-01", "swing-02", "swing-03"],
  swing_b: ["swing-04", "swing-05", "swing-06", "swing-07"],
} as const;

export type SwordidledarkClip = keyof typeof SWORDIDLEDARK_FRAMES;
