// GENERATED by scripts/build_tiles.py -- do not edit by hand.
// Regenerate with: npm run assets

/** One drawn tile atlas per biome, keyed by the biome's own name. */
export const TILES_TEXTURE_KEY = {
  grove: "tilesGrove",
  ruins: "tilesRuins",
  crypt: "tilesCrypt",
} as const;

/** Every frame a tile atlas carries, in sheet order. */
export const TILES_FRAMES = [
  "grass0",
  "grass1",
  "grass2",
  "dirt0",
  "dirt1",
  "path0",
  "path1",
  "stone0",
  "stone1",
  "stone2",
  "water",
  "wall",
] as const;

/** Tiles are drawn at world scale; this must equal TILE. */
export const TILES_SIZE = 32 as const;
