// GENERATED by scripts/build_atlas.py -- do not edit by hand.
// Regenerate with: npm run assets

export const VILLAGERS_TEXTURE_KEY = "villagers" as const;

/** How tall the character itself is inside the frame box, 0..1.
 *  Cells are padded by trails and motion range, so this -- not the frame
 *  height -- is what two characters must be compared on to size them
 *  relative to each other. */
export const VILLAGERS_BODY_RATIO = 0.88938 as const;

/** Every frame shares this source box, so one origin works for all of them. */
export const VILLAGERS_FRAME_SIZE = { width: 201, height: 226 } as const;

/** Origin on the body centre and its feet. */
export const VILLAGERS_ANCHOR = { x: 0.60697, y: 0.99558 } as const;

export const VILLAGERS_FRAMES = {
  a: ["elder0", "smith0", "apothecary0", "hearth0"],
  b: ["villager0", "villager1", "villager2", "villager3"],
} as const;

export type VillagersClip = keyof typeof VILLAGERS_FRAMES;
