// GENERATED by scripts/build_atlas.py -- do not edit by hand.
// Regenerate with: npm run assets

export const VILLAGERSSIDE_TEXTURE_KEY = "villagersSide" as const;

/** How tall the character itself is inside the frame box, 0..1.
 *  Cells are padded by trails and motion range, so this -- not the frame
 *  height -- is what two characters must be compared on to size them
 *  relative to each other. */
export const VILLAGERSSIDE_BODY_RATIO = 0.92918 as const;

/** Every frame shares this source box, so one origin works for all of them. */
export const VILLAGERSSIDE_FRAME_SIZE = { width: 203, height: 233 } as const;

/** Origin on the body centre and its feet. */
export const VILLAGERSSIDE_ANCHOR = { x: 0.62069, y: 1.00000 } as const;

export const VILLAGERSSIDE_FRAMES = {
  a: ["elder0", "smith0", "apothecary0", "hearth0"],
  b: ["villager0", "villager1", "villager2", "villager3"],
} as const;

export type VillagerssideClip = keyof typeof VILLAGERSSIDE_FRAMES;
