// GENERATED by scripts/build_atlas.py -- do not edit by hand.
// Regenerate with: npm run assets

export const VITALS_TEXTURE_KEY = "vitals" as const;

/** How tall the character itself is inside the frame box, 0..1.
 *  Cells are padded by trails and motion range, so this -- not the frame
 *  height -- is what two characters must be compared on to size them
 *  relative to each other. */
export const VITALS_BODY_RATIO = 0.46277 as const;

/** Every frame shares this source box, so one origin works for all of them. */
export const VITALS_FRAME_SIZE = { width: 93, height: 47 } as const;

/** Origin on the body centre and its vertical centre. */
export const VITALS_ANCHOR = { x: 0.49462, y: 0.48936 } as const;

export const VITALS_FRAMES = {
  bar: ["levelTrough", "levelPlate", "twinHealth", "twinMana"],
  mark: ["twinMark", "levelFlash"],
} as const;

export type VitalsClip = keyof typeof VITALS_FRAMES;
