// GENERATED by scripts/build_atlas.py -- do not edit by hand.
// Regenerate with: npm run assets

export const WARDENSLAM_TEXTURE_KEY = "wardenSlam" as const;

/** How tall the character itself is inside the frame box, 0..1.
 *  Cells are padded by trails and motion range, so this -- not the frame
 *  height -- is what two characters must be compared on to size them
 *  relative to each other. */
export const WARDENSLAM_BODY_RATIO = 0.90825 as const;

/** Every frame shares this source box, so one origin works for all of them. */
export const WARDENSLAM_FRAME_SIZE = { width: 416, height: 485 } as const;

/** Origin on the body centre and its feet. */
export const WARDENSLAM_ANCHOR = { x: 0.52644, y: 0.97938 } as const;

export const WARDENSLAM_FRAMES = {
  a: ["f-00", "f-01", "f-02", "f-03"],
  b: ["f-04", "f-05", "f-06", "f-07"],
} as const;

export type WardenslamClip = keyof typeof WARDENSLAM_FRAMES;
