// GENERATED by scripts/build_atlas.py -- do not edit by hand.
// Regenerate with: npm run assets

export const WARDENATTACK_TEXTURE_KEY = "wardenAttack" as const;

/** How tall the character itself is inside the frame box, 0..1.
 *  Cells are padded by trails and motion range, so this -- not the frame
 *  height -- is what two characters must be compared on to size them
 *  relative to each other. */
export const WARDENATTACK_BODY_RATIO = 0.98035 as const;

/** Every frame shares this source box, so one origin works for all of them. */
export const WARDENATTACK_FRAME_SIZE = { width: 361, height: 458 } as const;

/** Origin on the body centre and its feet. */
export const WARDENATTACK_ANCHOR = { x: 0.45706, y: 0.98908 } as const;

export const WARDENATTACK_FRAMES = {
  a: ["f-00", "f-01", "f-02", "f-03"],
  b: ["f-04", "f-05", "f-06", "f-07"],
} as const;

export type WardenattackClip = keyof typeof WARDENATTACK_FRAMES;
