// GENERATED by scripts/build_atlas.py -- do not edit by hand.
// Regenerate with: npm run assets

export const WARDENDEATH_TEXTURE_KEY = "wardenDeath" as const;

/** How tall the character itself is inside the frame box, 0..1.
 *  Cells are padded by trails and motion range, so this -- not the frame
 *  height -- is what two characters must be compared on to size them
 *  relative to each other. */
export const WARDENDEATH_BODY_RATIO = 0.82618 as const;

/** Every frame shares this source box, so one origin works for all of them. */
export const WARDENDEATH_FRAME_SIZE = { width: 387, height: 489 } as const;

/** Origin on the body centre and its feet. */
export const WARDENDEATH_ANCHOR = { x: 0.52455, y: 0.99591 } as const;

export const WARDENDEATH_FRAMES = {
  a: ["f-00", "f-01", "f-02", "f-03"],
  b: ["f-04", "f-05", "f-06", "f-07"],
} as const;

export type WardendeathClip = keyof typeof WARDENDEATH_FRAMES;
